version: "3.7"

services:
  pasarela:
    build: .
    ports:
      - "8090:8090"
    environment:
      RUTA_ESTACIONES_URL: http://estaciones:8070/estaciones
      RUTA_ALQUILERES_URL: http://alquileres:8080/api/alquileres
      RUTA_USUARIOS_URL: http://usuarios:5268/api/usuarios
  
  estaciones:
    build: ../estaciones-2-HervasLopez/
    ports:
      - "8070:8070"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/estaciones?authSource=admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo  
      - rabbitmq
      
  alquileres:
    build: ../alquileres-HervasLopez/
    ports:
      - "8080:8080"
    environment:
      DATABASE_CONNECTION_STRING: jdbc:mysql://user:password@mysql:3306/citybike
      
    depends_on:
      - mysql  
     
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: practica
      MYSQL_DATABASE: citybike
      MYSQL_USER: user
      MYSQL_PASSWORD: password  
      
  usuarios:
    build: ../usuarios/UsuariosAPI
    ports: 
      - "5268:5268"
    environment: 
      - MONGO_CONNECTION_STRING=mongodb://root:example@mongo:27017/usuarios.net?authSource=admin
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  
      - "15672:15672" 
      
volumes:
  mongo_data:

